/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Cloudflare bindings (DB, FONTS, ASSETS) reach SSR code through
// Astro.locals.runtime.env. `Env` is generated by `wrangler types`.
// ADMIN_EMAILS is merged in here (a comma-separated allowlist for the takedown
// action) so it survives a `wrangler types` regen of worker-configuration.d.ts.
interface __BaseEnv_Env {
  ADMIN_EMAILS?: string;
  // Google OAuth (optional: social sign-in is enabled only when both are set).
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  // Resend API key for transactional email (password reset). Optional: without
  // it, reset emails no-op (the rest of auth still works).
  RESEND_API_KEY?: string;
}
type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}
