/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Cloudflare bindings (DB, FONTS, ASSETS) reach SSR code through
// Astro.locals.runtime.env. `Env` is generated by `wrangler types`.
type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}
