/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Cloudflare bindings (DB, FONTS, ASSETS) reach SSR code through
// Astro.locals.runtime.env. `Env` is generated by `wrangler types`.
// ADMIN_EMAILS is merged in here (a comma-separated allowlist for the takedown
// action) so it survives a `wrangler types` regen of worker-configuration.d.ts.
interface __BaseEnv_Env {
  ADMIN_EMAILS?: string;
}
type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}
