name: duckadrift
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  adr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Stephen551/duckadrift@v0
